### ISSUE TITLE
How to run Nightmare on Alpine Linux (Docker)?

### ISSUE THREAD

**Issue by SaekiRaku** [segmentio/nightmare#1470]
I have read the issue of #224 to run Nightmare headlessly based on node:9.2 (Ubuntu) image. But the image size is too large for me.

Then I tried to build the App based on image of node:9.2.0-alpine, but it seems that some package didn't exist in Alpine Linux, such as `xfonts` `libdbus`...

What should I do? Is it possible to run nightmare on Alpine ?

**Comment by SauloNunes** [comment]
Hey guys, anny follow on this issue?

**Comment by SaekiRaku** [comment]
> Hey guys, anny follow on this issue?
> @SauloNunes 

😢 Sadly, I have no more progress, and I give up at last. Because some packages like `xfonts` `libdbus` can't find in [Apline Linux Package](https://pkgs.alpinelinux.org/packages). The final solution that I put to use is running on CentOS with `Ansible + PM2`, so that I can deploy and running my project on a bunch of servers.

Here is my `Ansible Playbook` config, it shows what dependence package that I've installed. Hope it'll help.

```yml
# NightMare Headlessly 依赖
  - name: 安装 Xvfb
    yum: 
      name: Xvfb
      state: installed
  - name: 安装 xorg-x11-xkb-utils-devel.x86_64
    yum: 
      name: xorg-x11-xkb-utils-devel.x86_64
      state: installed
  - name: 安装 xorg-x11-apps.x86_64
    yum: 
      name: xorg-x11-apps.x86_64
      state: installed
  - name: 安装 clang
    yum: 
      name: clang
      state: installed
  - name: 安装 libdbusmenu-devel.x86_64
    yum: 
      name: libdbusmenu-devel.x86_64
      state: installed
  - name: 安装 libdbusmenu-gtk2-devel.x86_64
    yum: 
      name: libdbusmenu-gtk2-devel.x86_64
      state: installed
  - name: 安装 libnotify-devel.x86_64
    yum: 
      name: libnotify-devel.x86_64
      state: installed
  - name: 安装 libgnome-keyring.x86_64
    yum: 
      name: libgnome-keyring.x86_64
      state: installed
  - name: 安装 GConf2-devel.x86_64
    yum: 
      name: GConf2-devel.x86_64
      state: installed
  - name: 安装 libcap-devel.x86_64
    yum: 
      name: libcap-devel.x86_64
      state: installed
  - name: 安装 cups-devel.x86_64
    yum: 
      name: cups-devel.x86_64
      state: installed
  - name: 安装 libXtst-devel.x86_64
    yum: 
      name: libXtst-devel.x86_64
      state: installed
  - name: 安装 libXScrnSaver.x86_64
    yum: 
      name: libXScrnSaver.x86_64
      state: installed
  - name: 安装 gcc
    yum: 
      name: gcc
      state: installed
  - name: 安装 g++
    yum: 
      name: gcc-c++
      state: installed

  - name: 安装 pm2
    command: npm install -g pm2
```
